apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}
  labels:
    app: {{ include "my-chart.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "my-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-chart.name" . }}
    spec:
      containers:
        - name: java-catalog
          image: {{" .Values.java-catalog.image.repository "}}:{{" .Values.java-catalog.image.tag "}}
          ports:
            - containerPort: 8081
          env:
            - name: APP_ENV
              value: {{" .Values.java-catalog.env.APP_ENV "}}
            - name: APP_DEBUG
              value: {{" .Values.java-catalog.env.APP_DEBUG "}}
            - name: SERVER_ADDRESS
              value: {{" .Values.java-catalog.env.SERVER_ADDRESS "}}
            - name: SERVER_PORT
              value: {{" .Values.java-catalog.env.SERVER_PORT "}}
            - name: SPRING_DATASOURCE_URL
              value: {{" .Values.java-catalog.env.SPRING_DATASOURCE_URL "}}
