apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}
  labels:
    app: {{ include "my-chart.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "my-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-chart.name" . }}
    spec:
      containers:
        - name: python-discuss
          image: {{" .Values.python-discuss.image.repository "}}:{{" .Values.pythondiscuss.image.tag "}}
          ports:
            - containerPort: 8083
          env:
            - name: MONGODB_HOST
              value: {{" .Values.python-discuss.env.MONGODB_HOST "}}
            - name: MONGODB_PORT
              value: {{" .Values.python-discuss.env.MONGODB_PORT "}}
            - name: MONGODB_DB
              value: {{" .Values.python-discuss.env.MONGODB_DB "}}
            - name: PORT
              value: {{" .Values.python-discuss.env.PORT "}}
            - name: AUTH_SERVICE_URL
              value: {{" .Values.python-discuss.env.AUTH_SERVICE_URL "}}
