apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ferran-helm-progress
spec:
  serviceName: progress-service
  replicas: 3
  selector:
    matchLabels:
      role: progress
  template:
    metadata:
      labels:
        role: progress
    spec:
      containers:
      - name: progress
        image: mongo:latest
        args:
          - "--replSet"
          - "rs0"
        ports:
          - containerPort: 9000
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
