apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ferran-helm-go
spec:
  serviceName: go-service
  replicas: 3
  selector:
    matchLabels:
      role: go
  template:
    metadata:
      labels:
        role: go
    spec:
      containers:
      - name: go
        image: mongo:latest
        args:
          - "--replSet"
          - "rs0"
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
