apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "my-chart.fullname" . }}
  labels:
    app: {{ include "my-chart.name" . }}
spec:
  serviceName: {{ .Release.Name }}-mongo
  replicas: 3
  selector:
    matchLabels:
      app: {{ include "my-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-chart.name" . }}
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.mongo.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.mongo.storageSize }}
