pipeline {
    agent any
    parameters {
        string(name: 'USER', defaultValue: 'ferrytiuu', description: 'Username')
        string(name: 'TAG', defaultValue: 'latest', description: 'Version of the image')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'golang:1.21'
                    reuseNode true
                }
            }
            steps {
                sh 'go test ./...'
            }
        }
        stage('Build Docker Image') {
            steps { 
                script{
                 def dockerfile = 'Dockerfile'
                 app = docker.build("${params.USER}/go-auth:${params.TAG}", "-f Dockerfile .")
                }
            }
        }
         stage('Push image') {
            steps{
                script{
                    withDockerRegistry(credentialsId: 'ferran.dockerhub') {
                        app.push()
                    }
                }
            }
        }   
    }   
}